version: '3.8'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
  user-service:
    build: ./user-service
    ports:
      - "8081:8080"
  pet-service:
    build: ./pet-service
    ports:
      - "8082:8080"
  battle-service:
    build: ./battle-service
    ports:
      - "8083:8080"
  notification-service:
    build: ./notification-service
    ports:
      - "8084:8080"
  analytics-service:
    build: ./analytics-service
    ports:
      - "8085:8080"
